Fix some bugs :bug:
CouturierTristan/fast-react pull request #22
Opened 2020-10-20 13:28 UTC by DoBrcd

Solve #21

2020-10-20 13:42 UTC, Ailurus13 commented on lib/shortcuts.js
> +  const shortcuts = getAllByUser(userId);
Better use `getShortcut` from shortcuts.js

2020-10-20 14:37 UTC, DoBrcd commented on lib/shortcuts.js
> +  const shortcuts = getAllByUser(userId);
https://github.com/CouturierTristan/fast-react-bot/pull/22/commits/e8d30ad48af3469f3d0ae4ff28e03ce5dd5b2797
Look at this commit

2020-10-21 06:22 UTC, CouturierTristan requested changes

2020-10-21 06:22 UTC, CouturierTristan commented on lib/shortcuts.js
> +  const shortcuts = getAllByUser(userId);
We can now delete the file `default-react.js`

2020-10-21 08:04 UTC, DoBrcd commented on lib/shortcuts.js
> +  const shortcuts = getAllByUser(userId);
Done

2020-10-21 10:48 UTC, merged